resources:
  - name: source
    icon: git
    type: git
    source:
      uri: git@github.com:gideaworx/go-custom-path-server.git
      private_key: ((go-custom-path-server-deploy-key))

  - name: base-image-go
    icon: docker
    type: registry-image
    check_every: 12h
    source:
      repository: chainguard/go
      tag: latest

  - name: base-image-run
    icon: docker
    type: registry-image
    check_every: 12h
    source:
      repository: chainguard/glibc-dynamic
      tag: latest

  - name: image-builder
    icon: docker
    type: registry-image
    check_every: 999999h
    source:
      repository: concourse/oci-build-task
      tag: "0.11.1"

  - name: target-registry
    type: registry-image
    source:
      repository: registry.lab.verysmart.house/library/go-custom-path-server
      username: ((harbor-user))
      password: ((harbor-password))

jobs:
  - name: build-image
    serial: true
    plan:
      - in_parallel:
          - get: source
            trigger: true
          - get: base-image-go
            trigger: true
            params:
              format: oci
          - get: base-image-run
            trigger: true
            params:
              format: oci
          - get: image-builder
      - in_parallel:
          - task: build-image
            image: image-builder
            file: source/ci/build-image-task.yaml
            privileged: true
          - load_var: version
            file: source/.git/describe_ref
            reveal: true
      - put: target-registry
        attempts: 5
        params:
          image: image/image.tar
          version: ((.:version))
          bump_aliases: true
        get_params:
          skip_download: true

